# Limpieza del dataset (Data Cleaning)

In [120]:
import pandas as pd
import numpy as np



raw_dataset= pd.read_excel('25-testcar-2026-01-21.xlsx') #dataframe original

preprocessed_dataset = raw_dataset.copy() ###dataset a limpiar para trabajar luego



print("Tamanio = [filas, columnas]:", raw_dataset.shape)


pd.options.display.max_columns = None
raw_dataset.head()

Tamanio = [filas, columnas]: (4287, 67)

,Model Year,Vehicle Manufacturer Name,Veh Mfr Code,Represented Test Veh Make,Represented Test Veh Model,Test Vehicle ID,Test Veh Configuration #,Test Veh Displacement (L),Actual Tested Testgroup,Vehicle Type,Rated Horsepower,# of Cylinders and Rotors,Engine Code,Tested Transmission Type Code,Tested Transmission Type,# of Gears,Transmission Lockup?,Drive System Code,Drive System Description,Transmission Overdrive Code,Transmission Overdrive Desc,Equivalent Test Weight (lbs.),Axle Ratio,N/V Ratio,Shift Indicator Light Use Cd,Shift Indicator Light Use Desc,Test Number,Test Originator,Analytically Derived FE?,ADFE Test Number,ADFE Total Road Load HP,ADFE Equiv. Test Weight (lbs.),ADFE N/V Ratio,Test Procedure Cd,Test Procedure Description,Test Fuel Type Cd,Test Fuel Type Description,Test Category,THC (g/mi),CO (g/mi),CO2 (g/mi),NOx (g/mi),PM (g/mi),CH4 (g/mi),N2O (g/mi),RND_ADJ_FE,FE_UNIT,FE Bag 1,FE Bag 2,FE Bag 3,FE Bag 4,DT-Inertia Work Ratio Rating,DT-Absolute Speed Change Ratg,DT-Energy Economy Rating,Target Coef A (lbf),Target Coef B (lbf/mph),Target Coef C (lbf/mph**2),Set Coef A (lbf),Set Coef B (lbf/mph),Set Coef C (lbf/mph**2),Aftertreatment Device Cd,Aftertreatment Device Desc,Police - Emergency Vehicle?,Averaging Group ID,Averaging Weighting Factor,Averaging Method Cd,Averging Method Desc
0,2025,aston martin,ASX,Aston Martin,DB12 V8,5723PT5601,0,4.0,RASXV04.0AES,Car,680,8.0,177850,A,Automatic,8,Y,R,"2-Wheel Drive, Rear",2,Top gear ratio < 1,4500,3.08,24.8,1,Not eqipped,RASX10082337,MFR,No,NaN,NaN,NaN,NaN,21,Federal fuel 2-day exhaust (w/can load),61,Tier 2 Cert Gasoline,FTP,0.0256,0.536,484.329,0.008,NaN,0.0089,0.0039,18.3,MPG,17.8185,17.0058,21.6199,NaN,-0.100,-0.200,-0.350,53.24,0.2228,0.0221,5.67,0.0083,0.0221,TWC,Three-way catalyst,N,NaN,NaN,N,No averaging
1,2025,aston martin,ASX,Aston Martin,DB12 V8,5723PT5601,0,4.0,RASXV04.0AES,Car,680,8.0,177850,A,Automatic,8,Y,R,"2-Wheel Drive, Rear",2,Top gear ratio < 1,4500,3.08,24.8,1,Not eqipped,RASX10082338,MFR,No,NaN,NaN,NaN,NaN,3,HWFE,61,Tier 2 Cert Gasoline,HWY,0.0007,0.040,283.235,0.007,NaN,NaN,NaN,31.3,MPG,NaN,NaN,NaN,NaN,8.720,7.090,-0.420,53.24,0.2228,0.0221,5.67,0.0083,0.0221,TWC,Three-way catalyst,N,NaN,NaN,N,No averaging
2,2025,aston martin,ASX,Aston Martin,DBX 707,8841PT8473,0,4.0,PASXJ04.0AEX,Both,707,8.0,177950,A,Automatic,9,Y,4,4-Wheel Drive,2,Top gear ratio < 1,5500,3.27,22.0,1,Not eqipped,PASX10073957,MFR,No,NaN,NaN,NaN,NaN,21,Federal fuel 2-day exhaust (w/can load),61,Tier 2 Cert Gasoline,FTP,0.0156,0.150,486.750,0.011,0.0004,0.0040,NaN,18.5,MPG,17.7311,17.8284,20.4728,NaN,-0.840,-1.000,-0.380,60.68,-0.3286,0.0373,-4.88,-0.5318,0.0367,TWC,Three-way catalyst,N,NaN,NaN,N,No averaging
3,2025,aston martin,ASX,Aston Martin,DBX 707,8841PT8473,0,4.0,PASXJ04.0AEX,Both,707,8.0,177950,A,Automatic,9,Y,4,4-Wheel Drive,2,Top gear ratio < 1,5500,3.27,22.0,1,Not eqipped,PASX10073958,MFR,No,NaN,NaN,NaN,NaN,3,HWFE,61,Tier 2 Cert Gasoline,HWY,0.0000,0.020,331.480,0.003,NaN,NaN,NaN,27.2,MPG,NaN,NaN,NaN,NaN,-5.030,-4.160,-1.210,60.68,-0.3286,0.0373,-4.88,-0.5318,0.0367,TWC,Three-way catalyst,N,NaN,NaN,N,No averaging
4,2025,aston martin,ASX,Aston Martin,Vanquish,370TT7334,0,5.2,SASXV05.2AMV,Car,825,12.0,AM34A/,A,Automatic,8,N,R,"2-Wheel Drive, Rear",2,Top gear ratio < 1,4500,2.93,22.6,1,Not eqipped,SASX10087770,MFR,No,NaN,NaN,NaN,NaN,21,Federal fuel 2-day exhaust (w/can load),61,Tier 2 Cert Gasoline,FTP,0.0170,0.826,546.351,0.025,NaN,0.0080,0.0050,16.4,MPG,15.6150,15.5160,19.1550,NaN,1.617,0.912,0.033,49.17,0.3527,0.0226,-0.57,-0.0029,0.0128,TWC,Three-way catalyst,N,NaN,NaN,N,No averaging

## Limpieza 
#### Irrelevancia no aporta informacion
1. Borrar año, todos los test son en 2025 
2. Columna "FE_UNIT" solo tiene 1 valor "mpg"
3. Borrar uno del par [Code / Desc] en cualitativas nominales por _redundancia_ , aportan la misma informacion.

In [122]:

columnas_borrar = [ 
    #no aportan informacion
    "Model Year",
    "FE_UNIT",
    #dejando el codigo porque es entendible
    'Drive System Description',
    'Transmission Overdrive Desc',
    'Tested Transmission Type', 
    
    #dejando la descripcion (mas legible)
    'Shift Indicator Light Use Cd', 
    'Test Procedure Cd', 
    'Test Fuel Type Cd',
    'Aftertreatment Device Cd',
    'Averaging Method Cd'
]

preprocessed_dataset.drop(columns=columnas_borrar, inplace=True, errors='ignore')

print("Columnas restantes:", len(preprocessed_dataset.columns))

Columnas restantes: 57

In [123]:
print("Tamanio = [filas, columnas]:", preprocessed_dataset.shape)

Tamanio = [filas, columnas]: (4287, 57)

## Nulos

In [124]:
resumen_nulos = pd.DataFrame({
    'Nulos': preprocessed_dataset.isna().sum(),
    'Porcentaje (%)': (preprocessed_dataset.isna().sum() / len(preprocessed_dataset) * 100).round(2)
})

display(resumen_nulos[resumen_nulos['Nulos'] > 0])

                                Nulos  Porcentaje (%)
# of Cylinders and Rotors         670           15.63
ADFE Test Number                 4075           95.05
ADFE Total Road Load HP          4075           95.05
ADFE Equiv. Test Weight (lbs.)   4075           95.05
ADFE N/V Ratio                   4075           95.05
THC (g/mi)                        958           22.35
CO (g/mi)                         884           20.62
CO2 (g/mi)                        724           16.89
NOx (g/mi)                        885           20.64
PM (g/mi)                        3898           90.93
CH4 (g/mi)                       1122           26.17
N2O (g/mi)                       2063           48.12
RND_ADJ_FE                        221            5.16
FE Bag 1                         2423           56.52
FE Bag 2                         2423           56.52
FE Bag 3                         2834           66.11
FE Bag 4                         3899           90.95
DT-Inertia Work Ratio Rating      695           16.21
DT-Absolute Speed Change Ratg     695           16.21
DT-Energy Economy Rating          695           16.21
Aftertreatment Device Desc        670           15.63
Averaging Group ID               4212           98.25
Averaging Weighting Factor       4212           98.25

In [125]:
preprocessed_dataset["# of Cylinders and Rotors"].value_counts()
preprocessed_dataset["# of Cylinders and Rotors"].isna().sum()
# 670 registros son nulos. Deben ser los electricos

np.int64(670)

In [126]:
null_cylinders = preprocessed_dataset.copy()

null_cylinders = null_cylinders[null_cylinders["# of Cylinders and Rotors"].isna()]

display(null_cylinders)

,Vehicle Manufacturer Name,Veh Mfr Code,Represented Test Veh Make,Represented Test Veh Model,Test Vehicle ID,Test Veh Configuration #,Test Veh Displacement (L),Actual Tested Testgroup,Vehicle Type,Rated Horsepower,# of Cylinders and Rotors,Engine Code,Tested Transmission Type Code,# of Gears,Transmission Lockup?,Drive System Code,Transmission Overdrive Code,Equivalent Test Weight (lbs.),Axle Ratio,N/V Ratio,Shift Indicator Light Use Desc,Test Number,Test Originator,Analytically Derived FE?,ADFE Test Number,ADFE Total Road Load HP,ADFE Equiv. Test Weight (lbs.),ADFE N/V Ratio,Test Procedure Description,Test Fuel Type Description,Test Category,THC (g/mi),CO (g/mi),CO2 (g/mi),NOx (g/mi),PM (g/mi),CH4 (g/mi),N2O (g/mi),RND_ADJ_FE,FE Bag 1,FE Bag 2,FE Bag 3,FE Bag 4,DT-Inertia Work Ratio Rating,DT-Absolute Speed Change Ratg,DT-Energy Economy Rating,Target Coef A (lbf),Target Coef B (lbf/mph),Target Coef C (lbf/mph**2),Set Coef A (lbf),Set Coef B (lbf/mph),Set Coef C (lbf/mph**2),Aftertreatment Device Desc,Police - Emergency Vehicle?,Averaging Group ID,Averaging Weighting Factor,Averging Method Desc
8,BMW,BMX,BMW,230i Coupe,8C99708,0,2.000,RBMXJ02.0M48,Both,255,NaN,B48B20O1G42S,SA,8,Y,R,2,3750,2.81,24.0,Not eqipped,RBMX10080494,MFR,No,NaN,NaN,NaN,NaN,Federal fuel 3-day exhaust,Tier 2 Cert Gasoline,FTP,0.013069,0.271895,255.251505,0.020702,NaN,0.002597,0.001027,34.3,31.689722,33.787985,37.336223,NaN,-0.038391,-0.120544,-1.004588,43.10,-0.1170,0.01980,14.10,0.1260,0.01706,NaN,N,NaN,NaN,No averaging
9,BMW,BMX,BMW,230i Coupe,8C99708,0,2.000,RBMXJ02.0M48,Both,255,NaN,B48B20O1G42S,SA,8,Y,R,2,3750,2.81,24.0,Not eqipped,RBMX10080495,MFR,No,NaN,NaN,NaN,NaN,HWFE,Tier 2 Cert Gasoline,HWY,0.000579,0.064103,172.313178,0.002622,NaN,0.000044,NaN,50.9,NaN,NaN,NaN,NaN,1.923341,1.654827,-0.483045,43.10,-0.1170,0.01980,14.10,0.1260,0.01706,NaN,N,NaN,NaN,No averaging
144,BMW,BMX,BMW,Countryman SE ALL4 (18'' Wheels),7N32897,1,0.001,SBMXV00.0U2X,Car,302,NaN,XE2B01N0U25X,A,1,N,A,1,5000,1.00,139.9,Not eqipped,SBMX10085645,MFR,No,NaN,NaN,NaN,NaN,Charge Depleting UDDS,Electricity,CD,NaN,NaN,NaN,NaN,NaN,NaN,NaN,139.3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,37.00,0.1720,0.01940,2.30,-0.0210,0.01963,NaN,N,NaN,NaN,No averaging
145,BMW,BMX,BMW,Countryman SE ALL4 (18'' Wheels),7N32897,1,0.001,SBMXV00.0U2X,Car,302,NaN,XE2B01N0U25X,A,1,N,A,1,5000,1.00,139.9,Not eqipped,SBMX10085646,MFR,No,NaN,NaN,NaN,NaN,Charge Depleting Highway,Electricity,CD,NaN,NaN,NaN,NaN,NaN,NaN,NaN,131.8,NaN,NaN,NaN,NaN,NaN,NaN,NaN,37.00,0.1720,0.01940,2.30,-0.0210,0.01963,NaN,N,NaN,NaN,No averaging
146,BMW,BMX,BMW,Countryman SE ALL4 (18'' Wheels),7N32897,2,0.001,SBMXV00.0U2X,Car,302,NaN,XE2B01N0U25X,A,1,N,A,1,5000,1.00,139.9,Not eqipped,SBMX10085647,MFR,No,NaN,NaN,NaN,NaN,Charge Depleting UDDS,Electricity,CD,NaN,NaN,NaN,NaN,NaN,NaN,NaN,145.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,32.20,0.1580,0.01941,-3.10,-0.0230,0.01934,NaN,N,NaN,NaN,No averaging
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4282,Wuhan Lotus Cars Co,WHN,Lotus,ELETRE S Performance,GIC_C10_6119,0,0.001,SWHNV00.0LEB,Car,603,NaN,LEB,A,1,N,A,1,6000,1.00,9.2,Not eqipped,SWHN10086785,MFR,No,NaN,NaN,NaN,NaN,CVS 75 and later (w/o can. load),Electricity,FTP,NaN,0.000000,0.000000,0.000000,NaN,0.000000,0.000000,NaN,NaN,NaN,NaN,NaN,0.000000,0.000000,0.000000,49.19,0.1899,0.02100,-8.08,-0.0412,0.02130,NaN,N,NaN,NaN,No averaging
4283,Wuhan Lotus Cars Co,WHN,Lotus,ELETRE S Performance,GIC_C10_6119,0,0.001,SWHNV00.0LEB,Car,603,NaN,LEB,A,1,N,A,1,6000,1.00,9.2,Not eqipped,SWHN10086806,MFR,No,NaN,NaN,NaN,NaN,HWFE,Electricity,HWY,NaN,0.000000,0.000000,0.000000,NaN,0.000000,0.000000,NaN,NaN,NaN,NaN,NaN,5.117000,4.241000,-0.135000,49.19,0.1899,0.02100,-8.08,-0.0412,0.02130,NaN,N,NaN,NaN,No averaging
4284,Wuhan Lotus Cars Co,WHN,Lotus,ELETRE S Performance,GIC_C10_6119,0,0.001,SWHNV00.0LEB,Car,603,NaN,LEB,A,1,N,A,1,6000,1.00,9.2,Not eqipped,SWHN10086818,MFR,No,NaN,NaN,NaN,NaN,US06,Electricity,US06,NaN,0.000000,0.000000,0.000000,NaN,0.000000,0.000000,NaN,NaN,NaN,NaN,NaN,0.000000,0.000000,0.000000,49.19,0.1899,0.02100,-7.96,0.0127,0.02060,NaN,N,NaN,NaN,No averaging
4285,Wuhan Lotus Cars Co,WHN,Lotus,ELETRE S Performance,GIC_C10_6119,0,0.001,SWHNV00.0LEB,Car,603,NaN,LEB,A,1,N,A,1,6000,1.00,9.2,Not eqipped,SWHN10086822,MFR,No,NaN,NaN,NaN,NaN,SC03,Electricity,SC03,NaN,0.000000,0.000000,0.000000,NaN,0.000000,0.000000,NaN,NaN,NaN,NaN,NaN,0.754000,-1.033000,0.087000,49.19,0.1899,0.02100,-8.08,-0.0412,0.02130,NaN,N,NaN,NaN,No averaging
4286,Wuhan Lotus Cars Co,WHN,Lotus,ELETRE S Performance,GIC_C10_6119,0,0.001,SWHNV00.0LEB,Car,603,NaN,LEB,A,1,N,A,1,6000,1.00,9.2,Not eqipped,SWHN10086826,MFR,No,NaN,NaN,NaN,NaN,Charge Depleting 20 Degree F FTP,Electricity,CD,NaN,NaN,NaN,NaN,NaN,NaN,NaN,39.7,NaN,NaN,NaN,NaN,NaN,NaN,NaN,49.19,0.1899,0.02100,-8.08,-0.0412,0.02130,NaN,N,NaN,NaN,No averaging

In [127]:
null_cylinders["Test Fuel Type Description"].value_counts()

Test Fuel Type Description
Electricity             654
Hydrogen 5               10
Tier 2 Cert Gasoline      6
Name: count, dtype: int64

In [128]:
preprocessed_dataset["Aftertreatment Device Desc"].isna().sum()

np.int64(670)

La ausencia (NaN) de valor en la columna _"# of Cylinders and Rotors"_ es debido a que los automoviles no tienen motor de combustion interna. Son 100% electricos o usan combustible de hidrogeno.

Para nosotros entender mejor el dominiio:
- los motores a combustion usan cilidros para comprimir y quemar mezcla de aire y combustible para mover pistones.
  

En relacion con _"Aftertreatment Device Desc"_ : tiene tambien 670 nulos, ya que la columna describe los dispositivos postratamiento de gases de escape. En electricos no hay combustion, y en hidrocarburos, tampoco se tiene canio de escape, ni requiere dispositivos postratamiento (catalizadores de tres vias, o filtros de particulas diesel).


En relacion con  _"Tested Transmission Type Code"_ : se encontraron los siguientes valores 
- Electricity             654
- Hydrogen 5               10
- Tier 2 Cert Gasoline      6

El unico que nos falta entender es _"Tier 2 Cert Gasoline"_ , el combustible se haya en 6 tests que no tienen cilindros. 

Tier 2: Es la normativa de la *EPA* y la regulacion ambiental para estándares federales de emisiones para vehículos y combustibles bajo la ley _Clean Air Act_.

El tipo de combustible es usado para las pruebas el "Cert Gasoline" es una nafta formulada en laboratorio según tolerancias exactas de laboratorio.

In [ ]:

filas_raras = preprocessed_dataset[
    (preprocessed_dataset['# of Cylinders and Rotors'].isna()) & 
    (preprocessed_dataset['Test Fuel Type Description'] == 'Tier 2 Cert Gasoline')
]

display(filas_raras)

,Vehicle Manufacturer Name,Veh Mfr Code,Represented Test Veh Make,Represented Test Veh Model,Test Vehicle ID,Test Veh Configuration #,Test Veh Displacement (L),Actual Tested Testgroup,Vehicle Type,Rated Horsepower,# of Cylinders and Rotors,Engine Code,Tested Transmission Type Code,# of Gears,Transmission Lockup?,Drive System Code,Transmission Overdrive Code,Equivalent Test Weight (lbs.),Axle Ratio,N/V Ratio,Shift Indicator Light Use Desc,Test Number,Test Originator,Analytically Derived FE?,ADFE Test Number,ADFE Total Road Load HP,ADFE Equiv. Test Weight (lbs.),ADFE N/V Ratio,Test Procedure Description,Test Fuel Type Description,Test Category,THC (g/mi),CO (g/mi),CO2 (g/mi),NOx (g/mi),PM (g/mi),CH4 (g/mi),N2O (g/mi),RND_ADJ_FE,FE Bag 1,FE Bag 2,FE Bag 3,FE Bag 4,DT-Inertia Work Ratio Rating,DT-Absolute Speed Change Ratg,DT-Energy Economy Rating,Target Coef A (lbf),Target Coef B (lbf/mph),Target Coef C (lbf/mph**2),Set Coef A (lbf),Set Coef B (lbf/mph),Set Coef C (lbf/mph**2),Aftertreatment Device Desc,Police - Emergency Vehicle?,Averaging Group ID,Averaging Weighting Factor,Averging Method Desc
8,BMW,BMX,BMW,230i Coupe,8C99708,0,2.0,RBMXJ02.0M48,Both,255,NaN,B48B20O1G42S,SA,8,Y,R,2,3750,2.81,24.0,Not eqipped,RBMX10080494,MFR,No,NaN,NaN,NaN,NaN,Federal fuel 3-day exhaust,Tier 2 Cert Gasoline,FTP,0.013069,0.271895,255.251505,0.020702,NaN,0.002597,0.001027,34.3,31.689722,33.787985,37.336223,NaN,-0.038391,-0.120544,-1.004588,43.100,-0.11700,0.019800,14.100,0.12600,0.017060,NaN,N,NaN,NaN,No averaging
9,BMW,BMX,BMW,230i Coupe,8C99708,0,2.0,RBMXJ02.0M48,Both,255,NaN,B48B20O1G42S,SA,8,Y,R,2,3750,2.81,24.0,Not eqipped,RBMX10080495,MFR,No,NaN,NaN,NaN,NaN,HWFE,Tier 2 Cert Gasoline,HWY,0.000579,0.064103,172.313178,0.002622,NaN,0.000044,NaN,50.9,NaN,NaN,NaN,NaN,1.923341,1.654827,-0.483045,43.100,-0.11700,0.019800,14.100,0.12600,0.017060,NaN,N,NaN,NaN,No averaging
2522,MAZDA,TKX,MAZDA,CX-5,8EBPYUG1-026,0,2.5,JTKXT02.5CDB,Truck,187,NaN,8PYUGAAA,A,6,Y,F,2,4000,4.62,33.7,Not eqipped,JTKX10081761,MFR,No,NaN,NaN,NaN,NaN,Federal fuel 2-day exhaust (w/can load),Tier 2 Cert Gasoline,FTP,0.006014,0.088190,298.163000,0.006215,NaN,0.001819,0.000112,29.6,27.895600,29.157600,32.123400,NaN,-0.432446,-0.314201,-0.111379,36.338,0.11447,0.025809,11.415,-0.02042,0.025830,NaN,N,NaN,NaN,No averaging
2523,MAZDA,TKX,MAZDA,CX-5,8EBPYUG1-026,0,2.5,JTKXT02.5CDB,Truck,187,NaN,8PYUGAAA,A,6,Y,F,2,4000,4.62,33.7,Not eqipped,JTKX10081762,MFR,No,NaN,NaN,NaN,NaN,HWFE,Tier 2 Cert Gasoline,HWY,0.000000,0.033290,216.207000,0.003315,NaN,0.000187,0.000000,40.9,NaN,NaN,NaN,NaN,1.431849,0.862839,-0.595758,36.338,0.11447,0.025809,11.415,-0.02042,0.025830,NaN,N,NaN,NaN,No averaging
2524,MAZDA,TKX,MAZDA,CX-5,8EBPYUG1-026,1,2.5,JTKXT02.5CDB,Truck,187,NaN,8PYUGAAA,A,6,Y,F,2,4000,4.62,33.3,Not eqipped,JTKX10081763,MFR,No,NaN,NaN,NaN,NaN,Federal fuel 2-day exhaust (w/can load),Tier 2 Cert Gasoline,FTP,0.006623,0.089620,296.533000,0.005494,NaN,0.001978,0.000212,29.7,28.160100,29.157600,32.477600,NaN,-0.171376,-0.121835,-0.370352,35.293,0.18848,0.024425,11.094,0.04705,0.024359,NaN,N,NaN,NaN,No averaging
2525,MAZDA,TKX,MAZDA,CX-5,8EBPYUG1-026,1,2.5,JTKXT02.5CDB,Truck,187,NaN,8PYUGAAA,A,6,Y,F,2,4000,4.62,33.3,Not eqipped,JTKX10081764,MFR,No,NaN,NaN,NaN,NaN,HWFE,Tier 2 Cert Gasoline,HWY,0.000000,0.038260,214.988000,0.003951,NaN,0.000282,0.000070,41.1,NaN,NaN,NaN,NaN,1.465824,1.322815,-0.263698,35.293,0.18848,0.024425,11.094,0.04705,0.024359,NaN,N,NaN,NaN,No averaging

BMW: Al tratarse de homologaciones de sistemas híbridos donde la potencia motriz primaria reportada en esa corrida proviene del tren de tracción eléctrico, el fabricante o el sistema de carga de la EPA omitió el conteo de pistones térmicos en la ficha técnica del ensayo, a pesar de que el generador auxiliar utiliza nafta convencional.

MAZDA: Este vehículo utiliza un motor rotativo Wankel de 830 cc como extensor de rango (range extender). Un motor Wankel no tiene cilindros ni pistones alternativos; funciona mediante un rotor triangular que gira dentro de una cámara epitrocoidal. en los formularios de homologación electrónica de la EPA muchas marcas registran  exclusivamente el conteo de cilindros convencionales. Al no tener cilindros con pistones convencionales, el fabricante dejó el campo vacío (NaN) en lugar de consignar el conteo de rotores.

Conclusion:
Se clasifican como casos particulares de motorizaciones alternativas e híbridas complejas (motores rotativos Wankel y omisiones de trenes híbridos) registradas dentro de la categoría Tier 2 Cert Gasoline

###  ADFE 
Son campos que registran información técnica únicamente cuando la economía de combustible no se midió físicamente en el dinamómetro, sino que fue calculada mediante un modelo analíticamente derivado.

La decisión correcta es conservarlas documentadas y excluirlas de los análisis estadísticos generales .

---

### Gases contaminantes
Los 7 tipos de gases representan emisiones de escape medidas en _gramos por milla (g/mi)_.
-   los electricos no emiten gases contaminantes.
-   distintos tipos de ensayos "Test Purpose Code": La EPA divide los ensayos entre pruebas destinadas exclusivamente a calcular la economía de combustible (Fuel Economy tests, código 31) y pruebas completas de certificación de emisiones (Emission certification, código 01 o 33). Los tests diseñados solo para certificar MPG no siempre cuantifican todo el panel de gases.

--- 

### RND_ADJ_FE y CD

Rounded Adjusted Fuel Economy (economía de combustible ajustada y redondeada oficial de la prueba, medida en MPG). Este campo falta en pruebas CD (Charge-Depleting), un protocolo de prueba diseñado exclusivamente para vehículos híbridos enchufables (PHEV).

Consiste en iniciar el ensayo con la batería al 100% y circular hasta agotarla por completo, midiendo principalmente el consumo eléctrico por milla (kW-hr/mi o MPGe).

Durante esta fase de descarga eléctrica, no se calcula un MPG tradicional de combustible líquido ajustado para la etiqueta de combustión convencional en esa celda específica, originando el valor en blanco.

---


### FE... son pruebas
Son las mediciones de MPG obtenidas en cada una de las "bolsas" (Bags) o fases transitorias de recolección de gases durante la prueba.

La presencia de estas bolsas coincide con el tipo de procedimiento de ensayo _"Test Procedure Description"_ por eso faltan valores. En ciclo urbano estan las diferentes "FE BAGS", mientras que en los Ciclos de Ruta (HWY / HFET) es un ensayo continuo de velocidad crucero en autopista, sin paradas intermedias ni fases de arranque en frío. No utiliza la recolección fraccionada por bolsas.

---
### DT 
- DT-Inertia Work Ratio Rating: calificación de la relación de trabajo de inercia.
- DT-Absolute Speed Change Ratg: calificación del seguimiento del perfil de velocidad.
- DT-Energy Economy Rating: índice de eficiencia energética de la traza de rodillos. 
  
    Estas variables son métricas de control de calidad exclusivas de un ensayo físico corrido sobre rodillos de dinamómetro. Cuando un ensayo es derivado analíticamente (ADFE), o cuando se utiliza información heredada de homologación previa (carry-over) sin volver a rodar el auto en la pista de rodillos, no existe una traza de dinamómetro que calificar.
---
  
### Averaging Group ID, Averaging Weighting Factor
Identifican los grupos de ensayo y los factores de ponderación cuando se aplican metodologías de promediado de emisiones y consumo de flota.

Solo se completan cuando un fabricante vincula un conjunto de pruebas de ciudad o ruta de distintas configuraciones técnicas bajo un mismo grupo ponderado para el cumplimiento del promedio corporativo ante las normas CAFE del Departamento de Transporte (DOT).

## Faltantes
Faltantes estructurales(MNAR): Ocurre cuando la ausencia responde a una razón del dominio.
En el caso de el MPG en las pruebas CD.

Conservaremos los nulos en el DataFrame y restringir la muestra a las observaciones disponibles únicamente para las hipótesis que requieran esa variable específica.

## Control de Registros Duplicados

In [130]:
preprocessed_dataset.duplicated().sum()

np.int64(0)

## Parsing de Texto, Unidades y Transformaciones Categorías

In [131]:
#buscar numeros en las filas que sean texto