# VERIFICAR RELACIONES ANTES DE LIMPIAR COLUMNAS

In [ ]:

import pandas as pd
import numpy as np


df = pd.read_excel('25-testcar-2026-01-21.xlsx')

- Se puede dejar **_Codigos_** (si vamos a trabajar con numeros) o **_Descripciones_** (si queremos la informacion)

En las siguientes `CROSS TABLES` se ve para que valor de codigo, se relaciona con cada descripcion. Si son `1:1` no aporta informacion tener 2 ya que siignifican lo mismo.

In [ ]:


pd.crosstab(df["Tested Transmission Type"], df["Tested Transmission Type Code"])

Tested Transmission Type Code,A,AM,AMS,CVT,M,OT,SA,SCV
Tested Transmission Type,,,,,,,,
Automated Manual,0,52,0,0,0,0,0,0
Automated Manual- Selectable (e.g. Automated Manual with paddles),0,0,485,0,0,0,0,0
Automatic,1639,0,0,0,0,0,0,0
Continuously Variable,0,0,0,490,0,0,0,0
Manual,0,0,0,0,128,0,0,0
Other,0,0,0,0,0,102,0,0
Selectable Continuously Variable (e.g. CVT with paddles),0,0,0,0,0,0,0,171
Semi-Automatic,0,0,0,0,0,0,1220,0

In [12]:

pd.crosstab(df["Drive System Description"], df["Drive System Code"])

Drive System Code           4     A     F   P    R
Drive System Description
2-Wheel Drive, Front        0     0  1393   0    0
2-Wheel Drive, Rear         0     0     0   0  957
4-Wheel Drive             405     0     0   0    0
All Wheel Drive             0  1459     0   0    0
Part-time 4-Wheel Drive     0     0     0  73    0

In [13]:
pd.crosstab(df["Transmission Overdrive Desc"], df["Transmission Overdrive Code"])

Transmission Overdrive Code    1     2
Transmission Overdrive Desc
No gear ratio < 1            668     0
Top gear ratio < 1             0  3619

In [14]:


pd.crosstab(df["Shift Indicator Light Use Desc"], df["Shift Indicator Light Use Cd"])

Shift Indicator Light Use Cd             1   2  3   5
Shift Indicator Light Use Desc
Equipped, not shifted by SIL             0  77  0   0
Equipped, shifted by SIL                 0   0  9   0
Equipped, shifted by survey schedule     0   0  0  55
Not eqipped                           4146   0  0   0