# VERIFICAR RELACIONES ANTES DE LIMPIAR COLUMNAS

In [2]:

import pandas as pd
import numpy as np


df = pd.read_excel('25-testcar-2026-01-21.xlsx')

- Se puede dejar **_Codigos_** (si vamos a trabajar con numeros) o **_Descripciones_** (si queremos la informacion)

En las siguientes `CROSS TABLES` se ve para que valor de codigo, se relaciona con cada descripcion. Si son `1:1` no aporta informacion tener 2 ya que siignifican lo mismo.

In [3]:


pd.crosstab(df["Tested Transmission Type"], df["Tested Transmission Type Code"])

Tested Transmission Type Code,A,AM,AMS,CVT,M,OT,SA,SCV
Tested Transmission Type,,,,,,,,
Automated Manual,0,52,0,0,0,0,0,0
Automated Manual- Selectable (e.g. Automated Manual with paddles),0,0,485,0,0,0,0,0
Automatic,1639,0,0,0,0,0,0,0
Continuously Variable,0,0,0,490,0,0,0,0
Manual,0,0,0,0,128,0,0,0
Other,0,0,0,0,0,102,0,0
Selectable Continuously Variable (e.g. CVT with paddles),0,0,0,0,0,0,0,171
Semi-Automatic,0,0,0,0,0,0,1220,0

In [4]:

pd.crosstab(df["Drive System Description"], df["Drive System Code"])

Drive System Code           4     A     F   P    R
Drive System Description
2-Wheel Drive, Front        0     0  1393   0    0
2-Wheel Drive, Rear         0     0     0   0  957
4-Wheel Drive             405     0     0   0    0
All Wheel Drive             0  1459     0   0    0
Part-time 4-Wheel Drive     0     0     0  73    0

In [5]:
pd.crosstab(df["Transmission Overdrive Desc"], df["Transmission Overdrive Code"])

Transmission Overdrive Code    1     2
Transmission Overdrive Desc
No gear ratio < 1            668     0
Top gear ratio < 1             0  3619

In [6]:


pd.crosstab(df["Shift Indicator Light Use Desc"], df["Shift Indicator Light Use Cd"])

Shift Indicator Light Use Cd             1   2  3   5
Shift Indicator Light Use Desc
Equipped, not shifted by SIL             0  77  0   0
Equipped, shifted by SIL                 0   0  9   0
Equipped, shifted by survey schedule     0   0  0  55
Not eqipped                           4146   0  0   0

In [7]:

pd.crosstab(df["Test Procedure Description"], df["Test Procedure Cd"])

Test Procedure Cd,2,3,11,21,25,31,77,81,83,84,85,86,90,95
Test Procedure Description,,,,,,,,,,,,,,
CVS 75 and later (w/o can. load),78,0,0,0,0,0,0,0,0,0,0,0,0,0
California fuel 2-day exhaust (w/can load),0,0,0,0,11,0,0,0,0,0,0,0,0,0
Charge Depleting 20 Degree F FTP,0,0,0,0,0,0,0,0,0,0,0,23,0,0
Charge Depleting Highway,0,0,0,0,0,0,0,0,0,239,0,0,0,0
Charge Depleting SC03,0,0,0,0,0,0,0,0,0,0,3,0,0,0
Charge Depleting UDDS,0,0,0,0,0,0,0,237,0,0,0,0,0,0
Charge Depleting US06,0,0,0,0,0,0,0,0,3,0,0,0,0,0
Cold CO,0,0,224,0,0,0,0,0,0,0,0,0,0,0
Federal fuel 2-day exhaust (w/can load),0,0,0,923,0,0,0,0,0,0,0,0,0,0
Federal fuel 3-day exhaust,0,0,0,0,0,341,0,0,0,0,0,0,0,0
HWFE,0,1340,0,0,0,0,0,0,0,0,0,0,0,0
Multi-Cycle Test (MCT),0,0,0,0,0,0,190,0,0,0,0,0,0,0
SC03,0,0,0,0,0,0,0,0,0,0,0,0,0,263
US06,0,0,0,0,0,0,0,0,0,0,0,0,412,0

In [8]:

pd.crosstab(df["Test Fuel Type Description"], df["Test Fuel Type Cd"])

Test Fuel Type Cd,19,26,27,28,38,46,47,48,50,61,62
Test Fuel Type Description,,,,,,,,,,,
CARB LEV3 E10 Premium Gasoline,0,0,0,0,0,0,2,0,0,0,0
CARB LEV3 E10 Regular Gasoline,0,0,0,0,0,1,0,0,0,0,0
Cold CO E10 Regular Gasoline (Tier 3),0,0,0,2,0,0,0,0,0,0,0
Cold CO Premium (Tier 2),0,0,57,0,0,0,0,0,0,0,0
Cold CO Regular (Tier 2),0,160,0,0,0,0,0,0,0,0,0
E85 (85% Ethanol 15% EPA Unleaded Gasoline),0,0,0,0,12,0,0,0,0,0,0
Electricity,0,0,0,0,0,0,0,0,0,0,654
Federal Cert Diesel 7-15 PPM Sulfur,150,0,0,0,0,0,0,0,0,0,0
Hydrogen 5,0,0,0,0,0,0,0,0,10,0,0
Tier 2 Cert Gasoline,0,0,0,0,0,0,0,0,0,3236,0
Tier 3 E10 Regular Gasoline (9 RVP @Low Alt.),0,0,0,0,0,0,0,3,0,0,0